--- 
- name: Disabling swap in temporary maner - command swapoff
  command: swapoff -a 
- name: Disabling swap in persistent maner - /etc/fstab
  replace:
    regexp: '^/swap*'
    path: /etc/fstab
    replace: '#swap'
#shell: sudo sed -i '/swap / s/^\(.*\)$/#\1/g' /etc/fstab
