---
- name: Ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755
- name: update of repos
  apt:
    update_cache: yes
#- name: cleaning tree dependencies
#  shell: 'kill -9 $(lsof /var/lib/dpkg/lock-frontend | cut -d " " -f 2)'
- name: install containerd apt-transport-https curl
  apt: 
    name: "{{ item.name }}" 
    state: present
    force_apt_get: yes
  loop: "{{ simple_packages }}"
- name: install haproxy keepalived
  apt:
    name: "{{ item.name }}"
    state: present
    force_apt_get: yes
  loop: "{{ ha_packages }}"
- name: Ensure directory /etc/containerd exist
  file: 
    path: /etc/containerd
    recurse: yes
    state: directory
- name: Generate default configuration
  shell:  containerd config default | sudo tee /etc/containerd/config.toml
  notify: Restart containerd 
