---
- name: repository key configuration
  apt_key:
    url: "{{ repository_key_k8s }}"
    state: present
- name: Adding kubernetes repos and update cache
  apt_repository:
    state: present
    repo: "{{ repository_deb_k8s }}"
    update_cache: yes
- name: installation of kubernetes packages
  apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    force_apt_get: yes
  loop: "{{ packages_k8s }}"
- name: hold packages
  dpkg_selections:
    name: "{{ item.name }}"
    selection: hold
  loop: "{{ packages_k8s }}"
