---
- name: import task to disable swap
  import_tasks: 01_disable_swap.yaml
- name: import task to load K8s modules
  import_tasks: 02_loading_k8s_module.yaml
- name: import task to install container runtime interface and oci
  import_tasks: 04_install_cri.yaml
- name: import task to configure K8s high availability packages
  import_tasks: 03_configure_ha_packages.yaml
- name: import task to install kubernetes packages
  import_tasks: 05_Install_k8s_packages.yaml
- name: import task to initialize kubernetes cluster
  import_tasks: 08_initializing_k8s_cluster.yaml
- name: Removing control plane taints on master nodes
  import_tasks: 06_remove_taints.yaml
